# -*- coding: utf-8 -*-
"""difference_equation_3.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V73F6uBYXVxtArkX0TeFg8bYjk68I3T_
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy

n = np.linspace(0, 19, 20)
y = np.loadtxt('filter_output.dat', dtype='double')

plt.stem(n, y,use_line_collection='True')
plt.title('Filter Output')
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()