# -*- coding: utf-8 -*-
"""impulse_response_5.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V73F6uBYXVxtArkX0TeFg8bYjk68I3T_
"""

import scipy
import matplotlib.pyplot as plt
import numpy as np

def delta(n):
    if n == 0:
        return 1
    else:
        return 0

def u(n):
    if n >= 0:
        return 1
    else:
        return 0

def h(n):
    return -4*delta(n) + 2*delta(n-1) + 5*u(n)*(-1/2)**n

vec_h = scipy.vectorize(h, otypes=[float])

N = np.linspace(0, 19, 20)
plt.stem(N, vec_h(N), use_line_collection='True')
plt.xlabel('$n$')
plt.ylabel('$h(n)$')
plt.grid()
plt.title('Filter Impulse Response')
plt.show()