# -*- coding: utf-8 -*-
"""impulse_response_5.8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V73F6uBYXVxtArkX0TeFg8bYjk68I3T_
"""

import numpy as np
import matplotlib.pyplot as plt

n = np.arange(14)
fn=(-1/2)**n
hn1=np.pad(fn, (0,2), 'constant', constant_values=(0))
hn2=np.pad(fn, (2,0), 'constant', constant_values=(0))
h = hn1+hn2

nh=len(h)
x=np.array([1.0,2.0,3.0,4.0,2.0,1.0])
nx = len(x)

y = np.zeros(nx+nh-1)

for k in range(0,nx+nh-1):
	for n in range(0,nx):
		if k-n >= 0 and k-n < nh:
			y[k]+=x[n]*h[k-n]

print(y)
#plots
plt.stem(range(0,nx+nh-1),y,use_line_collection = 'True')
plt.title('Filter Output using Convolution')
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()# minor

plt.show()